import streamlit as st
import requests
import pandas as pd
from fpdf import FPDF
import io
import openpyxl

# --- 1. PAYSTACK VERIFICATION FUNCTION ---
def is_premium(reference):
    if not reference or reference.strip() == "":
        return False
    
    url = f"https://api.paystack.co/transaction/verify/{reference}"
    headers = {"Authorization": f"Bearer {st.secrets['PAYSTACK_SECRET_KEY']}"}

    try:
        response = requests.get(url, headers=headers)
        data = response.json()

        if data.get("status") and data["data"]["status"] == "success":
            # 1,400,000 Kobo = 14,000 Naira
            if data["data"]["amount"] >= 1400000:
                return True
        return False
    except:
        return False

# --- 2. PROFESSIONAL PDF GENERATOR ---
def create_pdf(sorted_words, word_counts):
    pdf = FPDF()
    pdf.add_page()
    
    # Header: Branding
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, txt="WORD SORTER PRO", ln=1, align='C')
    pdf.set_font("Arial", 'I', 11)
    pdf.cell(0, 10, txt="Official Text Analysis & Frequency Report", ln=1, align='C')
    pdf.line(10, 32, 200, 32) 
    pdf.ln(15)
    
    # Table Headers
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(95, 10, txt=" Word / Phrase", border=1)
    pdf.cell(95, 10, txt=" Frequency", border=1, ln=1, align='C')
    
    # Table Data
    pdf.set_font("Arial", size=11)
    for word in sorted_words:
        # --- THE FIX IS HERE ---
        # This removes emojis or symbols that Arial can't print
        safe_word = str(word).encode('latin-1', 'ignore').decode('latin-1')
        count = str(word_counts[word])
        
        pdf.cell(95, 10, txt=f" {safe_word}", border=1)
        pdf.cell(95, 10, txt=f" {count}", border=1, ln=1, align='C')
    
    pdf.ln(10)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(0, 10, txt="Generated by Word Sorter Pro Premium Tier", align='R')
    
    return bytes(pdf.output())


# --- 3. SIDEBAR UI & LOGIC ---
st.sidebar.title("🚀 Word Sorter Pro")

# Payment Section
st.sidebar.subheader("💎 Premium Status")
user_ref = st.sidebar.text_input("Enter Paystack Reference", placeholder="e.g. T123456789")

# Verify the user
is_pro = is_premium(user_ref)

if is_pro:
    st.sidebar.success("Premium Active ✅")
else:
    st.sidebar.warning("Premium Features Locked")
    st.sidebar.link_button("Subscribe for ₦14,000", "https://paystack.shop/pay/ep6ce94qwz")

# Support Section
st.sidebar.divider()
st.sidebar.markdown("### 🛠 Support")
st.sidebar.info(
    "**Having trouble?**\n\n"
    "If your reference isn't working, contact us:\n"
    "📧 casezwebs@gmail.com"
)

# --- 4. MAIN APP INTERFACE ---
st.title("Text Analysis Dashboard")
input_text = st.text_area("Paste text here to sort:", height=200)

if input_text:
    # 1. Process all words in the background
    all_words = input_text.lower().split()
    word_counts = {word: all_words.count(word) for word in set(all_words)}
    full_sorted_list = sorted(word_counts.keys())
    total_count = len(full_sorted_list)

    
    

    # 2. Apply the Limit
    if is_pro:
        display_list = full_sorted_list
        st.subheader("✅ Full Premium Results")
        # --- THE FIX: Create a "Display Loop" to show word + number ---
        for word in display_list:
            count = word_counts[word]
            # This shows the word in bold and the number next to it
            st.write(f"**{word}**: {count}")
    
    else:
        # 1. Limit the display
        display_list = full_sorted_list[:10]
        st.subheader("🆓 Free Preview (First 10 words)")
        st.write(display_list)
        # --- THE FIX: Create a "Display Loop" to show word + number ---
        for word in display_list:
            count = word_counts[word]
            # This shows the word in bold and the number next to it
            st.write(f"**{word}**: {count}")
        
        st.warning(f"⚠️ You are viewing a limited preview (10 of {total_count} words).")

        # 2. THE BENEFITS SECTION (The "Pitch")
        st.markdown("---")
        st.markdown("### 💎 Why Upgrade to Premium?")
        
        col1, col2, col3 = st.columns(3)
        
        with col1:
            st.markdown("🚀 **Full Results**")
            st.caption("Remove the 10-word limit and analyze thousands of words instantly.")
            
        with col2:
            st.markdown("📄 **Pro PDF Reports**")
            st.caption("Download branded, table-formatted PDF reports for school or work.")
            
        with col3:
            st.markdown("📊 **Excel Export**")
            st.caption("Get your data in .xlsx format for advanced sorting and graphing.")

        # 3. Direct Call to Action
        st.link_button(
            label="🔥 Unlock All Features Now",
            url="https://paystack.shop/pay/ep6ce94qwz",  # Replace this with your actual Paystack link
            use_container_width=True
            )

    if is_pro:
        st.divider()
        st.markdown("### 📥 Premium Exports")
        # We pass the FULL list to the PDF, not the limited one!
        pdf_data = create_pdf(full_sorted_list, word_counts)
        st.download_button("Download Full PDF Report", data=pdf_data, file_name="full_report.pdf")

        # --- ENHANCED EXCEL GENERATION ---
        df = pd.DataFrame(list(word_counts.items()), columns=['Word/Phrase', 'Frequency (Count)'])
        
        excel_buffer = io.BytesIO()
        
        # We use 'xlsxwriter' here for better styling
        with pd.ExcelWriter(excel_buffer, engine='xlsxwriter') as writer:
            df.to_excel(writer, index=False, sheet_name='Analysis Report')
            
            workbook  = writer.book
            worksheet = writer.sheets['Analysis Report']

            # 1. Create a Header Format (Bold, Blue background, White text)
            header_format = workbook.add_format({
                'bold': True,
                'text_wrap': True,
                'valign': 'top',
                'fg_color': '#1D4E89',
                'font_color': 'white',
                'border': 1
            })

            # 2. Apply the header format to the top row
            for col_num, value in enumerate(df.columns.values):
                worksheet.write(0, col_num, value, header_format)

            # 3. Auto-adjust column width so nothing is cut off
            worksheet.set_column('A:A', 30) # Make 'Word' column wider
            worksheet.set_column('B:B', 15) # Make 'Frequency' column standard

            st.download_button(
            label="📊 Download Pro Excel Sheet",
            data=excel_buffer.getvalue(),
            file_name="Word_Sorter_Pro_Report.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )
