import streamlit as st
import requests
import pandas as pd
from fpdf import FPDF
import io

# --- 1. PAYSTACK VERIFICATION FUNCTION ---
def is_premium(reference):
    if not reference or reference.strip() == "":
        return False
    
    url = f"https://api.paystack.co/transaction/verify/{reference}"
    headers = {"Authorization": f"Bearer {st.secrets['PAYSTACK_SECRET_KEY']}"}

    try:
        response = requests.get(url, headers=headers)
        data = response.json()

        if data.get("status") and data["data"]["status"] == "success":
            # 1,400,000 Kobo = 14,000 Naira
            if data["data"]["amount"] >= 1400000:
                return True
        return False
    except:
        return False

# --- 2. PROFESSIONAL PDF GENERATOR ---
def create_pdf(sorted_words, word_counts):
    pdf = FPDF()
    pdf.add_page()
    
    # Header: Branding
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, txt="WORD SORTER PRO", ln=1, align='C')
    pdf.set_font("Arial", 'I', 11)
    pdf.cell(0, 10, txt="Official Text Analysis & Frequency Report", ln=1, align='C')
    pdf.line(10, 32, 200, 32) 
    pdf.ln(15)
    
    # Table Headers
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(95, 10, txt=" Word / Phrase", border=1)
    pdf.cell(95, 10, txt=" Frequency", border=1, ln=1, align='C')
    
    # Table Data
    pdf.set_font("Arial", size=11)
    for word in sorted_words:
        # --- THE FIX IS HERE ---
        # This removes emojis or symbols that Arial can't print
        safe_word = str(word).encode('latin-1', 'ignore').decode('latin-1')
        count = str(word_counts[word])
        
        pdf.cell(95, 10, txt=f" {safe_word}", border=1)
        pdf.cell(95, 10, txt=f" {count}", border=1, ln=1, align='C')
    
    pdf.ln(10)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(0, 10, txt="Generated by Word Sorter Pro Premium Tier", align='R')
    
    return bytes(pdf.output())
# --- EXCEL DEFINITION & BUTTON ---
# 1. Convert your word dictionary into a table (DataFrame)
df = pd.DataFrame(list(word_counts.items()), columns=['Word', 'Frequency'])
        
# 2. Create an "in-memory" file (buffer) to store the Excel data
excel_buffer = io.BytesIO()
        
# 3. Write the table to that buffer using the Excel engine
with pd.ExcelWriter(excel_buffer, engine='openpyxl') as writer:
    df.to_excel(writer, index=False, sheet_name='Word Analysis')
        
# 4. Create the download button for the user
st.download_button(
label="📊 Download Excel Analysis",
data=excel_buffer.getvalue(),
file_name="word_sorter_pro_data.xlsx",
mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
)

# --- 3. SIDEBAR UI & LOGIC ---
st.sidebar.title("🚀 Word Sorter Pro")

# Payment Section
st.sidebar.subheader("💎 Premium Status")
user_ref = st.sidebar.text_input("Enter Paystack Reference", placeholder="e.g. T123456789")

# Verify the user
is_pro = is_premium(user_ref)

if is_pro:
    st.sidebar.success("Premium Active ✅")
else:
    st.sidebar.warning("Premium Features Locked")
    st.sidebar.link_button("Subscribe for ₦14,000", "https://paystack.shop/pay/yjn6h0qdb9")

# Support Section
st.sidebar.divider()
st.sidebar.markdown("### 🛠 Support")
st.sidebar.info(
    "**Having trouble?**\n\n"
    "If your reference isn't working, contact us:\n"
    "📧 casezwebs@gmail.com"
)

# --- 4. MAIN APP INTERFACE ---
st.title("Text Analysis Dashboard")
input_text = st.text_area("Paste text here to sort:", height=200)

if input_text:
    # 1. Process all words in the background
    all_words = input_text.lower().split()
    word_counts = {word: all_words.count(word) for word in set(all_words)}
    full_sorted_list = sorted(word_counts.keys())
    total_count = len(full_sorted_list)

    # 2. Apply the Limit
    if is_pro:
        display_list = full_sorted_list
        st.subheader("✅ Full Premium Results")
    else:
        # 1. Limit the display
        display_list = full_sorted_list[:10]
        st.subheader("🆓 Free Preview (First 10 words)")
        st.write(display_list)
        
        st.warning(f"⚠️ You are viewing a limited preview (10 of {total_count} words).")

        # 2. THE BENEFITS SECTION (The "Pitch")
        st.markdown("---")
        st.markdown("### 💎 Why Upgrade to Premium?")
        
        col1, col2, col3 = st.columns(3)
        
        with col1:
            st.markdown("🚀 **Full Results**")
            st.caption("Remove the 10-word limit and analyze thousands of words instantly.")
            
        with col2:
            st.markdown("📄 **Pro PDF Reports**")
            st.caption("Download branded, table-formatted PDF reports for school or work.")
            
        with col3:
            st.markdown("📊 **Excel Export**")
            st.caption("Get your data in .xlsx format for advanced sorting and graphing.")

        # 3. Direct Call to Action
        st.button("Unlock All Features Now", on_click=lambda: st.sidebar.focus(), help="Click to go to the sidebar payment link")
    # 4. Handle Downloads
    if is_pro:
        st.divider()
        st.markdown("### 📥 Premium Exports")
        # We pass the FULL list to the PDF, not the limited one!
        pdf_data = create_pdf(full_sorted_list, word_counts)
        st.download_button("Download Full PDF Report", data=pdf_data, file_name="full_report.pdf")
